hostname: rancher.staging.csds.qld.edu.au
replicas: 1
tls: external
ingress:
  enabled: true
  ingressClassName: traefik
  extraAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"